### ISSUE TITLE
itt antiguo con campañas video-ads

### ISSUE THREAD

**Issue by rvargassanhueza** [RadioCooperativa/vistas#5]
se comienza a implementar itt antiguo (posición sobre el sitio) y se despliegan por detrás formatos de video ads.

modificado en utiles.listen.class

**Comment by rvargassanhueza** [comment]
- [x] Home Sticky
[Vista previa esc sinItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/home-test-video-banner.html)
[Vista previa esc oldItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/home-test-video-banner.html?google_preview=Z8ZLo99Pi_sY4dLz9AUw4e6o_AWIAYCAgKDn3tDnxgE&iu=1020719&gdfp_req=1&lineItemId=5350606289&creativeId=138308853542)
[Vista previa esc newItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/home-test-video-banner.html?google_preview=33tsmxoOjXQYv9Hz9AUwv-2o_AWIAYCAgKDn3tCxdQ&iu=1020719&gdfp_req=1&lineItemId=5351673753&creativeId=138309159765)
[Vista previa mov sin itt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_home-test-video-banner.html)
[Vista previa mov oldItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_home-test-video-banner.html?google_preview=-GriztPujYEYocnz9AUwoeWo_AWIAYCAgKDn3tD6WQ&iu=1020719&gdfp_req=1&lineItemId=5350606289&creativeId=138309007326)
[Vista previa mov newItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_home-test-video-banner.html?google_preview=kgR-Jq6O7e8Yvs7z9AUwvuqo_AWIAYCAgKDn3tDxDg&iu=1020719&gdfp_req=1&lineItemId=5351673753&creativeId=138309161349)
- [x] InRead
[Vista previa esc sinItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/nota-test-video-banner.html)
[Vista previa esc oldItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/nota-test-video-banner.html?google_preview=RUoc-Ks_kuoY_NTz9AUw_PCo_AWIAYCAgKDn3rDoLw&iu=1020719&gdfp_req=1&lineItemId=5350606289&creativeId=138308853542)
[Vista previa esc newItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/nota-test-video-banner.html?google_preview=o5QoAU4xs2wY_Nbz9AUw_PKo_AWIAYCAgKDn3rDNCg&iu=1020719&gdfp_req=1&lineItemId=5351673753&creativeId=138309159765)
[Vista previa mov sinItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_nota_test_video_banner.html)
[Vista previa mov newItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_nota_test_video_banner.html?google_preview=9y9hrmmxIDMYr9nz9AUwr_Wo_AWIAYCAgKDn3rDptwE&iu=1020719&gdfp_req=1&lineItemId=5351673753&creativeId=138309161349)
[Vista previa mov oldItt](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_nota_test_video_banner.html?google_preview=thxBpLbjaA4Yutrz9AUwuvao_AWIAYCAgKDn3rCJXw&iu=1020719&gdfp_req=1&lineItemId=5350606289&creativeId=138309007326)

**Comment by rvargassanhueza** [comment]
url vista esc:

http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/old-itt-video-banner.html

**Comment by rvargassanhueza** [comment]
`


<IMG SRC="________________" BORDER="0" HEIGHT="1" WIDTH="1" ALT="Advertisement" style="position:absolute; z-index:-10; top:-999em;">
    
    
    
    <style>
    #gam_container_01 {
        width: 100vw;
        height: 100vh;
        background: rgba(255, 255, 255, .9);
        top: 0;
        left: 0;
        z-index: 999999999;
        display: block;
        position: fixed;
    }
    
    .gam_container_02 {
        display: flex;
        min-height: 100vh;
        margin: 0;
    }
    
    .gam_container_03 {
        margin: auto;
        filter: drop-shadow(0 25px 25px rgba(0,0,0,0.10));
    }
    
    .gam_container_04 {
        display: block;
        width: 925px;
        height: 549px;
        background: rgba(255,0,0,0);
    }
    
    .gam_container_05 {
        position: absolute;
        z-index: 1;
        display: block;
        width: 925px;
        height: 520px;
    }
    
    .gam_container_06 {
        display: block;
        width: 925px;
        height: 520px;
        background: #fff;
    }
    
    .gam_container_06 img {
        display: block;
        width: 925px !important;
        height: 520px !important;
        margin: 0;
        padding: 0;
        border: none;
    }
    
    #gam_container_07 {
        background: rgba(66,66,66,1);
        border-top: 1px solid rgba(237,237,237,1);
        height: 30px;
        display: table;
        width: 100%;
    }
    
    .gam_container_08 {
        background-size: 25px;
        height: 30px;
        display: table;
        width: 100%;
    }
    
    .gam_position_initial,
    .gam_position_sticky {
        z-index: initial;
        bottom: initial;
        position: initial;
    }
    
    @media only screen and (max-height: 631px) and (min-height: 0px) {
        .gam_position_initial {
            position: initial !important;
            z-index: initial !important;
            bottom: initial !important;
        }
        .gam_position_sticky {
            position: sticky;
            z-index: 9999999999;
            bottom: 0;
        }
    }
    
    .gam_link_01 {
        z-index: 999999300;
        position: absolute;
        width: 925px;
        height: 520px;
        background: rgba(255,0,0,.0);
    }
    .gam_link_01 span {
        display: none;
    }
    
    .gam_link_02 {
        color: #ccc;
        display: block;
        font-family: 'Merriweather', serif;
        text-rendering: optimizeLegibility;
        letter-spacing: normal;
        text-transform: uppercase;
        font-style: normal;
        font-weight: normal;
        font-size: 13px;
        line-height: 30px;
        text-align: center;
        padding: 0;
        cursor: pointer;
        background: rgba(255,0,0,.0);
    }
    
    @media only screen and (max-width: 927px) and (min-width: 0) {
        .gam_link_02 {
            width: 100vw;
        }
    }
    
    a.gam_link_02 {
        color: rgba(194,194,194,1);
        -o-transition: color .15s ease-out, color .15s ease-in;
        -ms-transition: color .15s ease-out, color .15s ease-in;
        -moz-transition: color .15s ease-out, color .15s ease-in;
        -webkit-transition: color .15s ease-out, color .15s ease-in;
        transition: color .15s ease-out, color .15s ease-in;
    }
    
    a.gam_link_02:link,
    a.gam_link_02:visited {
        color: rgba(194,194,194,1);
        text-decoration: none;
    }
    
    a.gam_link_02:hover,
    a.gam_link_02:active {
        color: rgba(255,255,255,1);
        text-decoration: none;
    }
    
    .gam_button_01 {
        background: url('data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%0A%3C%21--%20Generator%3A%20A%20I%2021.1.0%2C%20SVG%20Export%20Plug-In%20.%20SVG%20Version%3A%206.00%20Build%200%29%20%20--%3E%0A%3Csvg%20version%3D%221.0%22%20id%3D%22Layer_1%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20xmlns%3Axlink%3D%22http%3A//www.w3.org/1999/xlink%22%20x%3D%220px%22%20y%3D%220px%22%0A%09%20viewBox%3D%220%200%20157.4%20157.4%22%20style%3D%22enable-background%3Anew%200%200%20157.4%20157.4%3B%22%20xml%3Aspace%3D%22preserve%22%3E%0A%3Cstyle%20type%3D%22text/css%22%3E%0A%09.st0%7Bfill%3A%23FFFFFF%3B%7D%0A%3C/style%3E%0A%3Cg%3E%0A%09%3Cg%3E%0A%09%09%3Ccircle%20class%3D%22st0%22%20cx%3D%2278.7%22%20cy%3D%2278.7%22%20r%3D%2278.7%22/%3E%0A%09%09%3Ccircle%20cx%3D%2278.7%22%20cy%3D%2278.7%22%20r%3D%2268%22/%3E%0A%09%3C/g%3E%0A%09%3Cpolygon%20class%3D%22st0%22%20points%3D%22104.9%2C40.4%2078.7%2C66.6%2052.5%2C40.4%2040.4%2C52.5%2066.6%2C78.7%2040.4%2C104.9%2052.5%2C117%2078.7%2C90.8%20104.9%2C117%20%0A%09%09117%2C104.9%2090.8%2C78.7%20117%2C52.5%20%09%22/%3E%0A%3C/g%3E%0A%3C/svg%3E%0A') no-repeat center center rgba(255,255,255,.0) ;
        background-size: 18px;
        background-position: center;
        display: inline-block;
        vertical-align: top;
        width: 30px;
        height: 30px;
        opacity: .3;
        -o-transition: all .15s ease-out, all .15s ease-in;
        -ms-transition: all .15s ease-out, all .15s ease-in;
        -moz-transition: all .15s ease-out, all .15s ease-in;
        -webkit-transition: all .15s ease-out, all .15s ease-in;
        transition: all .15s ease-out, all .15s ease-in;
    }
    
    .gam_link_02:hover .gam_button_01,
    .gam_link_02:active .gam_button_01 {
       opacity: 1;
    }
    
    .gam_underline_01 {
        border-bottom: 1px solid rgba(192, 192, 192, 0);
        height: 22px;
        display: inline-block;
        -webkit-transition: border 500ms ease;
        -moz-transition: border 500ms ease;
        -ms-transition: border 500ms ease;
        -o-transition: border 500ms ease;
        transition: border 500ms ease;
    }
    
    .gam_link_02:hover .gam_underline_01 {
        border-bottom: 1px solid rgba(192, 192, 192, 1);
    }
    
    .gam_border_01,
    .gam_border_02,
    .gam_border_03 {
        position: absolute;
        background: rgba(133,133,133,.35);
        /* COLOR DEL BORDE DEL ITT*/
    }
    
    .gam_border_01 {
        width: 1px;
        height: 520px;
        z-index: 999999303;
        margin: 0;
    }
    
    .gam_border_02 {
        width: 925px;
        height: 1px;
        z-index: 999999304;
        margin: 0;
    }
    
    .gam_border_03 {
        width: 1px;
        height: 520px;
        z-index: 999999305;
        margin: 0 0 0 calc(925px - 1px);
    }
    
    .gam_display {
        margin-top: initial !important;
    }
    
    .gam_display_none {
        margin-top: -999em;
    }
    </style>
    
    <div id='gam_container_01' class="gam_display_none">
        <div class="gam_container_02">
            <div class="gam_container_03">
                <div class="gam_container_04">
                    <div class="gam_border_01"></div>
                    <div class="gam_border_02"></div>
                    <div class="gam_border_03"></div>
                    <div class="gam_container_05">
                        <a href="%%CLICK_URL_ESC%%%%DEST_URL%%" target="_blank" class="gam_link_01">
                            <span><img src="%%FILE:JPG1%%" width="925" height="520" alt="Anuncio publicitario">Anuncio publicitario</span>
                        </a>
                    </div>
                    <div class="gam_container_06">
                        <img src="%%FILE:JPG1%%" width="1" height="1" alt="">
                    </div>
                    <div id="gam_container_07" class="gam_position_initial">
                        <div class="gam_container_08">
                            <a class="gam_link_02" onclick="gamHideLayer();"><span class="gam_button_01"></span><span class="gam_underline_01">Saltar Anuncio</span></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        (function() {
            document.getElementById("gam_container_07").classList.add("gam_position_sticky");
            document.getElementById("gam_container_07").classList.remove("gam_position_initial");
            document.getElementById("gam_container_01").classList.add("gam_display");
            document.getElementById("gam_container_01").classList.remove("gam_display_none");
            let gam_mensaje = {
                cmd: 'safe-frame',
                tipo: 'gam-bloque-itt',
                mensaje: 'itt',
                timeOut: 3.3,
                params: {
                    position: 'fixed',
                    display: 'block',
                    height: '100vh',
                    width: '100vw',
                    top: '0',
                    left: '0',
                    zIndex: '999999999'
                }
            };
            window.top.postMessage(gam_mensaje, '*');
        })();
    
    setTimeout(function() {gamHideLayer()}, 1000 * 15);
    
    function gamHideLayer() {

        let gam_mensaje = {
            cmd: 'safe-frame',
            tipo: 'gam-bloque-itt',
            mensaje: 'itt',
            cerrar: 1
        };
        window.top.postMessage(gam_mensaje, '*');
    }
    </script>`

**Comment by rvargassanhueza** [comment]
[Creatividad oldItt Esc](view-source:http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/creatividad-itt-esc.html)

**Comment by rvargassanhueza** [comment]
[creatividad-footer-mov-terceros.txt](https://github.com/RadioCooperativa/vistas/files/4531590/creatividad-footer-mov-terceros.txt)
[creatividad-itt-esc.txt](https://github.com/RadioCooperativa/vistas/files/4500877/creatividad-itt-esc.txt)
[creatividad-itt-mov.txt](https://github.com/RadioCooperativa/vistas/files/4500879/creatividad-itt-mov.txt)
[creatividad-Newitt-esc.txt](https://github.com/RadioCooperativa/vistas/files/4500880/creatividad-Newitt-esc.txt)
[creatividad-Newitt-mov.txt](https://github.com/RadioCooperativa/vistas/files/4500881/creatividad-Newitt-mov.txt)
[creatividad-itt-esc-terceros.txt](https://github.com/RadioCooperativa/vistas/files/4527103/creatividad-itt-esc-terceros.txt)
[creatividad-itt-mov-terceros.txt](https://github.com/RadioCooperativa/vistas/files/4527104/creatividad-itt-mov-terceros.txt)

**Comment by pdiaz-coop** [comment]
- [x] Home Sticky

[Vista previa esc skin 990x90](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/home-test-video-banner.html?google_preview=7DW1xnLKUHcYi_aG9QUwi5K8_AWIAYCAgKDngajfjwE&iu=1020719&gdfp_req=1&lineItemId=5333851153&creativeId=138307012413)
[Estado: OK]
[Nota: El skin no se ocupa en la portada]

[Vista previa esc portada falsa 1259x600](https://www.cooperativa.cl/?google_preview=pKs6AtU6CdYYjOaH9QUwjIK9_AWIAYCAgKDngbTo_QE&iu=1020719&gdfp_req=1&lineItemId=5241476087&creativeId=138296786037)
[Estado: 🔴 con problemas: falta actualizar la creatividad para que cuando se cierre se habilite el Home Sticky]
[Nota: La portada falsa solo se ocupa en la portada]

[Vista previa mov skin 320x150](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_home-test-video-banner.html?google_preview=wVPWUS-fxYEYisKC9QUwit63_AWIAYCAgKDn_q79bA&iu=1020719&gdfp_req=1&lineItemId=5355573341&creativeId=138309425330)
[Estado: OK]
[Nota: El skin no se ocupa en la portada]

[Vista previa mov footer 320x80](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_home-test-video-banner.html?google_preview=YpuHtAHsp5EY_M2C9QUw_Om3_AWIAYCAgKDn_u6uAw&iu=1020719&gdfp_req=1&lineItemId=5355587900&creativeId=138309461277)
[Estado: 🔴 con problemas: falta actualizar la creatividad para que cuando se cierre se habilite el Home Sticky]
[Nota: El footer 320x80 es poco probable que salga en portada]

--------------------------------------------------------

- [x] InRead

[Vista previa esc skin 990x90](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/nota-test-video-banner.html?google_preview=UhqHIbcm-UsY3_iG9QUw35S8_AWIAYCAgKDngajCOQ&iu=1020719&gdfp_req=1&lineItemId=5333851153&creativeId=138307012413)
[Estado: ⚠️OK en general. Hay que modificar la creatividad del skin para que no envíe InRead por detrás de la columna principal en el scroll]
[Nota: El skin se ocupa frecuentemente en los artículos]

[Vista previa mov skin 320x150](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_nota_test_video_banner.html?google_preview=833XNunA5xYY9-uC9QUw94e4_AWIAYCAgKDn_t6NKQ&iu=1020719&gdfp_req=1&lineItemId=5355573341&creativeId=138309425330)
[Estado: OK]
[Nota: El skin se ocupa frecuentemente en los artículos]

Vista previa mov portada falsa
[Estado: -]
[Nota: la portada falsa no se ocupa en los artículos ni en la portada. Se ocupa un ITT común]

[Vista previa mov footer 320x80](http://h2.cooperativa.cl/noticias/stat/publicidad/codes/vistas/m_nota_test_video_banner.html?google_preview=4sb4kZpPzTYYiOeC9QUwiIO4_AWIAYCAgKDn_t6oRA&iu=1020719&gdfp_req=1&lineItemId=5355587900&creativeId=138309461277)
[Estado: 🔴 con problemas: falta actualizar la creatividad para que cuando se cierre se habilite el InRead]

**Comment by rvargassanhueza** [comment]
se soluciona nueva problemática originada por el no control de la llegada de mensajes. Se implemeta solución con e.origin.startsWith(site)
