### ISSUE TITLE
optimización instancias sitio coop

### ISSUE THREAD

**Issue by rvargassanhueza** [RadioCooperativa/vistas#6]
Replicar instancias de sitio m360 en coop

**Comment by rvargassanhueza** [comment]
- [x] Directorio Instancia
- [x] Directorios Bloques

- Escritorio

- [x] Portada
- [x] Portadilla Mundo
- [x] Portadilla Pais
- [x] Portadilla Entretención
- [x] Portadilla Video
- [x] Portadilla Audio
- [x] Portadilla Foto
- [x] Portadilla Programas
- [x] Portadilla Taxonomicas
- [x] Articulo Noticia
- [x] Articulo Noticia Audio
- [x] Articulo Noticia Foto
- [x] Articulo Noticia Video
- [x] Articulo Noticia Infinito
- [x] Articulo Noticia Foto Infinito
- [x] Articulo Noticia Audio Infinito
- [x] Articulo Noticia Video Infinito
- [x] Articulo MaM
- [x] Articulo Multimedia Audio
- [x] Articulo Multimedia Foto
- [x] Articulo Multimedia Video
- [x] Plantillas /clist/ (Regiones)

- Móvil

- [x] Portada
- [x] Portadilla Mundo
- [x] Portadilla Pais
- [x] Portadilla Entretención
- [x] Portadilla Video
- [x] Portadilla Audio
- [x] Portadilla Foto
- [ ] Portadilla Programas
- [x] Portadilla Taxonomicas
- [x] Articulo Noticia
- [x] Articulo Noticia Audio
- [x] Articulo Noticia Foto
- [x] Articulo Noticia Video
- [x] Articulo Noticia Infinito
- [x] Articulo Noticia Foto Infinito
- [x] Articulo Noticia Audio Infinito
- [x] Articulo Noticia Video Infinito
- [x] Articulo MaM
- [x] Articulo Multimedia Audio
- [x] Articulo Multimedia Foto
- [x] Articulo Multimedia Video
- [x] Plantillas /clist/ (Regiones)

**Comment by Rebolledo-Rodolfo** [comment]
**Desagrupar Portadilla Multimedia en :**

- Portadilla Vídeo
- Portadilla Audio
- Portadilla Fotos

**Agregar:**

- Artículo Noticia
- Artículo MaM
- Plantillas /clist/ (Regiones)

**Agregar Secundarios**

- Plantilla Búsquedas - (/cache/)
- Radio en Vivo

**Comment by rvargassanhueza** [comment]
Listo, revisar.

**Comment by rvargassanhueza** [comment]
Lo que está dentro del recuadro rojo, se debe validar con los datos que se encuentran en GAM (claves).
![guia-par-clave-valor](https://user-images.githubusercontent.com/17125189/80761707-0e5a8000-8b09-11ea-847b-a94980da1c77.png)

**Comment by pdiaz-coop** [comment]
Reporte de errores:

· En coop_m_320x80_02 del primer artículo aparece una publicidad Adsense a pesar de estar en pateocinio la línea de prueba https://i.imgur.com/SykSufz.png

**Comment by Rebolledo-Rodolfo** [comment]
REVISIÓN VISTA : **Escritorio**
Revisión : Ok

**Plantillas**: Artículos

- [x] - Noticia
- [x] - MaM
- [x] - Video
- [x] - Audio
- [x] - Foto

**Plantillas**: Portadas

- [x] - Home
- [x] - Portadillas
- [x] - Tax
- [ ] - Search
- [ ] - Clist


**Urgentes**
- Sin Registros

**Secundarios**
- Home - Espacio Blanco al TOP en la Primera carga.
- Video Sticky se despliega al hacer srcoll-back a la posición de despliegue.
- Solucionar Error Promise.

> VM825 go.js:119 Uncaught (in promise) ReferenceError: initInread is not defined
> at callViews (VM825 go.js:119)
> at go (VM825 go.js:76)

**Comment by pdiaz-coop** [comment]
**REPORTE DE ERRORES:**

### ESC Artículo (normal):
Test aprobados con banners normales:

- [x] Seccion 1 (coop_seccion_1)
- [x] Tema 1 (coop_tema_1)
- [x] Subtema 1 (coop_subtema_1)
- [x] Bloques de anuncios (coop_bloque)
- [x] Timestamp (coop_ts)
- [x] Ternas

- En el primer artículo no se despliega el **coop_d_728x90_01**:
https://i.imgur.com/0ucIUHg.png

----------------------------------

- En el primer artículo no se despliega el **coop_d_728x90_03**:
https://i.imgur.com/svtRr8P.png

----------------------------------

- En los todos artículos del scroll de esta página:
http://h2.cooperativa.cl/noticias/mundo/bolivia/evo-morales/evo-morales-agradecio-al-papa-su-respaldo-a-causa-maritima-boliviana/2018-03-14/095951.html
se muestra el bloque **coop_d_990x90_02** equivocadamente, allí debe ir un **coop_d_728x90_01** (revisar el sitio actual de cooperativa).
https://i.imgur.com/Tu8UtPg.png
https://i.imgur.com/dkx2VHc.png
https://i.imgur.com/P1ZYtPj.png

----------------------------------

- En los todos artículos del scroll de esta página:
http://h2.cooperativa.cl/noticias/entretencion/musica/jose-luis-rodriguez/jennifer-lopez-revelo-que-un-director-le-pidio-que-le-mostrara-los-pechos/2018-03-15/191027.html
se muestra el bloque **coop_d_990x90_03** equivocadamente, allí debe ir un **coop_d_728x90_03** (revisar el sitio actual de cooperativa).
https://i.imgur.com/4Be9WWM.png
https://i.imgur.com/JwtQR9I.png
https://i.imgur.com/GlKp5xe.png

----------------------------------

### MOV Artículo (normal):
Test aprobados con banners normales:

- [x] Seccion 1 (coop_seccion_1)
- [x] Tema 1 (coop_tema_1)
- [x] Subtema 1 (coop_subtema_1)
- [x] Bloques de anuncios (coop_bloque)
- [x] Timestamp (coop_ts)
- [x] Ternas

- ~En coop_m_320x80_02 de el primer artículo aparece un AdExchange o AdSense a pesar de que la línea de pedido de prueba está en patrocinio https://i.imgur.com/SykSufz.png~

----------------------------------

- ~En los artículos normales, en el scroll, no veo el **coop_m_320x80_01** en ninguna nota:
https://i.imgur.com/H1T32AY.png
https://i.imgur.com/YDEFaK7.png~

----------------------------------

- ~En los artículos normales, en el scroll, en algunos artículos (no el primero) no se ve el **coop_m_320x80_02**:
https://i.imgur.com/HPOIGca.png
https://i.imgur.com/eo3HM5i.png~

----------------------------------

- ~En los artículos normales, al hacer el par-clave-valor: "coop_seccion_1" → "coop_pais", no me funciona. No se ven los banners de prueba en país. Probé con "coop_seccion_1" → "coop_entretencion" y tampoco me funcionó.~

~Probé con las siguientes páginas:
http://h2.cooperativa.cl/noticias/site/artic/20180314/pags-movil2/20180314111627.html
http://h2.cooperativa.cl/noticias/site/artic/20180316/pags-movil2/20180316094633.html~

----------------------------------
- ~En los artículos normales, al hacer el par-clave-valor: "coop_tema_1" → "ffaa_y_de_orden", no me funciona. No se ven los banners de prueba. Probé con "coop_tema_1" → "humor" y tampoco me funcionó.~

~Probé con las siguientes páginas:
http://h2.cooperativa.cl/noticias/site/artic/20180314/pags-movil2/20180314111627.html
http://h2.cooperativa.cl/noticias/site/artic/20180316/pags-movil2/20180316094633.html~

~Quizá este sea un posible error (entre "ff.aa._" y "ffaa_")~
![image](https://user-images.githubusercontent.com/64154524/81464526-87ed1080-9190-11ea-89b3-45e8d7f1e08a.png)

----------------------------------

- ~Al hacer la prueba con Timestamp (coop_ts) en articulo no lo considera, no se dirigen los banners para que se publiquen solo en esa página: 
https://i.imgur.com/BgZbK3d.png
https://i.imgur.com/uA6Rq8v.png
https://i.imgur.com/ksORVm6.png~

**Comment by Rebolledo-Rodolfo** [comment]
**REVISIÓN VISTA** : Movil
**Estado** : En Proceso

Plantillas: Artículos

- [x] - Noticia
- [x] - MaM
- [x] - Video
- [x] - Audio
- [x] - Foto

**Plantillas**: Portadas

- [x] - Home
- [x] - Portadillas
- [x] - Tax
- [ ] - Search
- [ ] - Clist

**Urgentes**

- ~Revisar Integración con ITT ( sticky corre detrás )~


**Secundarios**

- Integración con publicidad **externa** activa como vídeo sticky o In Read , se sobre escriben los players.

![photo_2020-05-07_23-18-31](https://user-images.githubusercontent.com/5281086/81367140-66215a00-90ba-11ea-97f4-2340dc9055c3.jpg)


 - Solucionar
VM825 go.js:119 Uncaught (in promise) ReferenceError: initInread is not defined
    at callViews (VM825 go.js:119)
    at go (VM825 go.js:76)

**Comment by fhuertavargas** [comment]
~Estado: En proceso.
**Plantilla: Taxonómica.**
**REVISIÓN VISTA: Escritorio.**
FIDs - all/noticia/video/foto/audio~
~- [x] fid_noticia~
~- [x] fid_all~
~- [x] fid_video~
~- [x] fid_foto~
~- [x] fid_audio~

~**REVISIÓN VISTA: Móvil.** vista móvil ejemplo /fid_noticia-movil2/~

~- [x] fid_noticia~
- [x] fid_all
- [x] fid_video
- [x] fid_foto
- [x] fid_audio

~**Comentarios: Escritorio**
url ref: http://h2.cooperativa.cl/noticias/site/tax/port/fid_noticia/cooperativataxport_4_11__1.html
Revisión despligues :~

~- [x] ITT: aparece correctamente [sólo FID noticia]~

- [ ] Lazy: No aparece

~- [x] VideoADS: No aparece~
~- [x] Sticky :testeado en otra url y sí funciona http://h2.cooperativa.cl/noticias/site/tax/port/fid_noticia/cooperativataxport_4_107__1.html~


~**Comentarios: Móvil**
url ref: http://h2.cooperativa.cl/noticias/site/tax/port/fid_noticia-movil2/cooperativataxport_4_11__1.html
Revisión despligues :~

~- [x] ITT: corregido~

~- [ ] Lazy: No aparece~

~- [ ] VideoADS: No aparece~

~ERROR: pubads_impl_2020043001.js?21066106:6 Exception in queued GPT command TypeError: Cannot read property 'addService' of null~


> REVISIÓN NOTA MÓVIL
> http://h2.cooperativa.cl/noticias/site/artic/20191213/pags-movil2/20191213182731.html
> Aparece sticky sin darle clic a leer noticia completa, sucede cuando cambia la resolución de la página

**Comment by rvargassanhueza** [comment]
> **REPORTE DE ERRORES:**
> 
> ### MOV Artículo (normal):
> * ~En coop_m_320x80_02 de el primer artículo aparece un AdExchange o AdSense a pesar de que la línea de pedido de prueba está en patrocinio https://i.imgur.com/SykSufz.png~
> 
> * ~En los artículos normales, en el scroll, no veo el **coop_m_320x80_01** en ninguna nota:
>   https://i.imgur.com/H1T32AY.png
>   https://i.imgur.com/YDEFaK7.png~
> 
> * ~En los artículos normales, en el scroll, en algunos artículos (no el primero) no se ve el **coop_m_320x80_02**:
>   https://i.imgur.com/HPOIGca.png
>   https://i.imgur.com/eo3HM5i.png~

![scroll-mobile-1](https://user-images.githubusercontent.com/17125189/81493957-c6f39280-9272-11ea-90c6-2797f1c82b98.png)
![scroll-mobile-2](https://user-images.githubusercontent.com/17125189/81493956-c5c26580-9272-11ea-9456-4d08c668e65b.png)


> 
> * ~En los artículos normales, al hacer el par-clave-valor: "coop_seccion_1" → "coop_pais", no me funciona. No se ven los banners de prueba en país. Probé con "coop_seccion_1" → "coop_entretencion" y tampoco me funcionó.~
> 
> ~Probé con las siguientes páginas:
> http://h2.cooperativa.cl/noticias/site/artic/20180314/pags-movil2/20180314111627.html
> http://h2.cooperativa.cl/noticias/site/artic/20180316/pags-movil2/20180316094633.html~
> 
> * ~En los artículos normales, al hacer el par-clave-valor: "coop_tema_1" → "ffaa_y_de_orden", no me funciona. No se ven los banners de prueba. Probé con "coop_tema_1" → "humor" y tampoco me funcionó.~
> 
> ~Probé con las siguientes páginas:
>http://h2.cooperativa.cl/noticias/site/artic/20180314/pags-movil2/20180314111627.html
>http://h2.cooperativa.cl/noticias/site/artic/20180316/pags-movil2/20180316094633.html~
> 
> ~Quizá este sea un posible error (entre "ff.aa._" y "ffaa_")
> ![image](https://user-images.githubusercontent.com/64154524/81464526-87ed1080-9190-11ea-89b3-45e8d7f1e08a.png)~
> 
> * ~Al hacer la prueba con Timestamp (coop_ts) en articulo no lo considera, no se dirigen los banners para que se publiquen solo en esa página:
>   https://i.imgur.com/BgZbK3d.png
>   https://i.imgur.com/uA6Rq8v.png
>   https://i.imgur.com/ksORVm6.png~
>

**Comment by rvargassanhueza** [comment]
> > **REPORTE DE ERRORES:**
> > ### MOV Artículo (normal):
> > 
> > * ~En coop_m_320x80_02 de el primer artículo aparece un AdExchange o AdSense a pesar de que la línea de pedido de prueba está en patrocinio https://i.imgur.com/SykSufz.png~
> > * ~En los artículos normales, en el scroll, no veo el **coop_m_320x80_01** en ninguna nota:
> >   https://i.imgur.com/H1T32AY.png
> >   https://i.imgur.com/YDEFaK7.png~
> > * ~En los artículos normales, en el scroll, en algunos artículos (no el primero) no se ve el **coop_m_320x80_02**:
> >   https://i.imgur.com/HPOIGca.png
> >   https://i.imgur.com/eo3HM5i.png~
> 
> ![scroll-mobile-1](https://user-images.githubusercontent.com/17125189/81493957-c6f39280-9272-11ea-90c6-2797f1c82b98.png)
> ![scroll-mobile-2](https://user-images.githubusercontent.com/17125189/81493956-c5c26580-9272-11ea-9456-4d08c668e65b.png)
> 
> > * ~En los artículos normales, al hacer el par-clave-valor: "coop_seccion_1" → "coop_pais", no me funciona. No se ven los banners de prueba en país. Probé con "coop_seccion_1" → "coop_entretencion" y tampoco me funcionó.~
> > 
> > ~Probé con las siguientes páginas:
> > http://h2.cooperativa.cl/noticias/site/artic/20180314/pags-movil2/20180314111627.html
> > http://h2.cooperativa.cl/noticias/site/artic/20180316/pags-movil2/20180316094633.html~
> > 
> > * ~En los artículos normales, al hacer el par-clave-valor: "coop_tema_1" → "ffaa_y_de_orden", no me funciona. No se ven los banners de prueba. Probé con "coop_tema_1" → "humor" y tampoco me funcionó.~
> > 
> > ~Probé con las siguientes páginas:
> > http://h2.cooperativa.cl/noticias/site/artic/20180314/pags-movil2/20180314111627.html
> > http://h2.cooperativa.cl/noticias/site/artic/20180316/pags-movil2/20180316094633.html~
> > ~Quizá este sea un posible error (entre "ff.aa._" y "ffaa_")
> > ![image](https://user-images.githubusercontent.com/64154524/81464526-87ed1080-9190-11ea-89b3-45e8d7f1e08a.png)~
> > 
> > * ~Al hacer la prueba con Timestamp (coop_ts) en articulo no lo considera, no se dirigen los banners para que se publiquen solo en esa página:
> >   https://i.imgur.com/BgZbK3d.png
> >   https://i.imgur.com/uA6Rq8v.png
> >   https://i.imgur.com/ksORVm6.png~

**Comment by rvargassanhueza** [comment]
> Estado: En proceso.
> **Plantilla: Taxonómica.**
> **REVISIÓN VISTA: Escritorio.**
> FIDs - all/noticia/video/foto/audio
> ~- [x] fid_noticia~
> ~- [x] fid_all~
> ~- [x] fid_video~
> ~- [x] fid_foto~
> ~- [x] fid_audio~
> 
> **REVISIÓN VISTA: Móvil.** vista móvil ejemplo /fid_noticia-movil2/
> 
> ~- [x] fid_noticia~
> ~- [x] fid_all~
> ~- [x] fid_video~
> ~- [x] fid_foto~
> ~- [x] fid_audio~
> 
> **Comentarios: Escritorio**
> url ref: http://h2.cooperativa.cl/noticias/site/tax/port/fid_noticia/cooperativataxport_4_11__1.html
> Revisión despligues :
> 
> * [x]  ITT: aparece correctamente [sólo FID noticia]
> * ~[x]  Lazy: No aparece~
> 
> ~- [x] VideoADS: No aparece~
> ~- [x] Sticky :testeado en otra url y sí funciona http://h2.cooperativa.cl/noticias/site/tax/port/fid_noticia/cooperativataxport_4_107__1.html~
> 
> **Comentarios: Móvil**
> url ref: http://h2.cooperativa.cl/noticias/site/tax/port/fid_noticia-movil2/cooperativataxport_4_11__1.html
> Revisión despligues :
> 
> ~- [x] ITT: corregido~
> 
> * ~[x]  Lazy: No aparece~
> * ~[x]  VideoADS: No aparece~

![lazy-tax-mob](https://user-images.githubusercontent.com/17125189/81495130-0a063380-927c-11ea-8f63-fe93ccc2dd7d.png)

![lazy-video-ads-mob](https://user-images.githubusercontent.com/17125189/81495195-8731a880-927c-11ea-813d-1a4f107727b5.png)


> 
> ERROR: pubads_impl_2020043001.js?21066106:6 Exception in queued GPT command TypeError: Cannot read property 'addService' of null
> 
> > REVISIÓN NOTA MÓVIL
> > http://h2.cooperativa.cl/noticias/site/artic/20191213/pags-movil2/20191213182731.html
> > Aparece sticky sin darle clic a leer noticia completa, sucede cuando cambia la resolución de la página
